// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxn3cE9SD32WGOC1nrVSLgNePK7RRvi48',
    appId: '1:642389630685:web:4913a343be5fe9f3660534',
    messagingSenderId: '642389630685',
    projectId: 'fir-ba8a7',
    authDomain: 'fir-ba8a7.firebaseapp.com',
    storageBucket: 'fir-ba8a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPVKAR_380ZdORdvgPPbMaxQCDIcBGVkc',
    appId: '1:642389630685:android:da4092c336eac664660534',
    messagingSenderId: '642389630685',
    projectId: 'fir-ba8a7',
    storageBucket: 'fir-ba8a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODz7Zxm7wEgV0WyRaEqCBm6XKTJGWPno',
    appId: '1:642389630685:ios:a1afee2eedbcfd69660534',
    messagingSenderId: '642389630685',
    projectId: 'fir-ba8a7',
    storageBucket: 'fir-ba8a7.appspot.com',
    iosClientId:
        '642389630685-i92khut2emgpal2u6ai94td1lief5lv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODz7Zxm7wEgV0WyRaEqCBm6XKTJGWPno',
    appId: '1:642389630685:ios:414b238216b99d31660534',
    messagingSenderId: '642389630685',
    projectId: 'fir-ba8a7',
    storageBucket: 'fir-ba8a7.appspot.com',
    iosClientId:
        '642389630685-24ktsil49sb78su1mffc225hh55alqin.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogger.RunnerTests',
  );
}
